In [ ]:
# Grid Search code

In [1]:
# importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns

In [2]:
# importing the dataser
os.chdir("C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources")

In [3]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [4]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  11021175    Male   42           121315          0
1  17782313    Male   53            67214          0
2  14603818  Female   59           111005          0
3  18188198  Female   39            53414          0
4  19357305    Male   39           114285          0

In [5]:
dataset.describe().transpose()

count          mean           std         min          25%  \
User ID          400.0  1.510090e+07  2.862593e+06  10016842.0  12605933.25   
Age              400.0  3.988500e+01  1.179660e+01        20.0        30.00   
EstimatedSalary  400.0  9.974823e+04  2.837436e+04     50075.0     76060.25   
Purchased        400.0  3.575000e-01  4.798640e-01         0.0         0.00   

                        50%          75%         max  
User ID          15098745.0  17412962.25  19996164.0  
Age                    40.0        51.00        60.0  
EstimatedSalary     99205.0    122748.00    149553.0  
Purchased               0.0         1.00         1.0

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
# splitting the dataset into x and y
X = dataset.iloc[:,[1,2,3]].values
y = dataset.iloc[:,4].values

In [8]:
X

array([['Male', 42, 121315],
       ['Male', 53, 67214],
       ['Female', 59, 111005],
       ...,
       ['Female', 25, 82560],
       ['Male', 55, 147667],
       ['Female', 54, 134972]], dtype=object)

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [12]:
#data preprocessing through column transformer and one hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(X))
print(x)

[[0.0 1.0 42 121315]
 [0.0 1.0 53 67214]
 [1.0 0.0 59 111005]
 ...
 [1.0 0.0 25 82560]
 [0.0 1.0 55 147667]
 [1.0 0.0 54 134972]]


In [13]:
from sklearn.preprocessing import StandardScaler    # to make the data in  standard format to read
sc = StandardScaler()
x=sc.fit_transform(x)

In [14]:
x

array([[-1.02020406,  1.02020406,  0.17951354,  0.76103154],
       [-1.02020406,  1.02020406,  1.11315372, -1.14804259],
       [ 0.98019606, -0.98019606,  1.622412  ,  0.39722026],
       ...,
       [ 0.98019606, -0.98019606, -1.26338491, -0.60652484],
       [-1.02020406,  1.02020406,  1.28290648,  1.69092048],
       [ 0.98019606, -0.98019606,  1.1980301 ,  1.24294916]])

In [17]:
# splitting the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [19]:
y_pred=classifier.predict(X_test)

In [20]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)

In [21]:
#applying k fold cross validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=X_train,y=y_train,cv=10) 

In [ ]:
accuracies

In [ ]:
accuracies.mean()

In [ ]:
accuracies.std()

In [ ]:
'''
#applying grid search to find the best model and best parameters
from sklearn.model_selection import GridSearchCV
parameters=[{'C':[1,10,100,1000],'kernel':['linear']},
           {'C':[1,10,100,1000],'kernel':['rbf'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
grid_search=GridSearchCV(estimator=classifier,
                        param_grid=parameters,
                        scoring='accuracy',
                        cv=10,
                        n_jobs=-1)
grid_search=grid_search.fit(X_train,y_train)
best_accuracy=grid_search.best_score_
best_parameters=grid_search.best_params_
'''

In [25]:
#applying grid search to find the best model and best parameters on knn
from sklearn.model_selection import GridSearchCV
parameters=[{'n_neighbors':[17,21,23,25]}] #[5,11,15,17]
grid_search=GridSearchCV(estimator=classifier,
                        param_grid=parameters,
                        scoring='accuracy',
                        cv=10,
                        n_jobs=-1)
grid_search=grid_search.fit(X_train,y_train)
best_accuracy=grid_search.best_score_
best_parameters=grid_search.best_params_

In [26]:
best_accuracy

0.5933333333333334

In [27]:
best_parameters

{'n_neighbors': 23}

In [28]:
# fitting kernel SVM to the training set
from sklearn.svm import SVC
classifier =SVC(kernel='rbf',random_state =0)
classifier.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [29]:
y_pred=classifier.predict(X_test)

In [30]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [31]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)

In [32]:
cm

array([[68,  0],
       [32,  0]], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.68

In [34]:
# applying cross validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=X_train,y=y_train,cv=10) 

In [35]:
accuracies

array([0.53333333, 0.63333333, 0.63333333, 0.63333333, 0.63333333,
       0.6       , 0.63333333, 0.63333333, 0.63333333, 0.6       ])

In [36]:
accuracies.mean()

0.6166666666666666

In [37]:
accuracies.std()

0.030731814857642953

In [38]:
#applying grid search to find the best model and best parameters
from sklearn.model_selection import GridSearchCV
parameters=[{'C':[1,10,100,1000],'kernel':['linear']},    
           {'C':[1,10,100,1000],'kernel':['rbf']}]      # furthur narrow down values on the basis of best_parameters
grid_search=GridSearchCV(estimator=classifier,
                        param_grid=parameters,
                        scoring='accuracy',
                        cv=10,
                        n_jobs=-1)
grid_search=grid_search.fit(X_train,y_train)
best_accuracy=grid_search.best_score_
best_parameters=grid_search.best_params_

In [39]:
best_accuracy

0.6299999999999999

In [40]:
best_parameters

{'C': 1, 'kernel': 'linear'}