In [2]:
# XG boost
import os
os.chdir("C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources")

In [3]:
os.getcwd()

'C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources'

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [6]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
dataset.describe().transpose()

count          mean           std          min  \
RowNumber        10000.0  5.000500e+03   2886.895680         1.00   
CustomerId       10000.0  1.569094e+07  71936.186123  15565701.00   
CreditScore      10000.0  6.505288e+02     96.653299       350.00   
Age              10000.0  3.892180e+01     10.487806        18.00   
Tenure           10000.0  5.012800e+00      2.892174         0.00   
Balance          10000.0  7.648589e+04  62397.405202         0.00   
NumOfProducts    10000.0  1.530200e+00      0.581654         1.00   
HasCrCard        10000.0  7.055000e-01      0.455840         0.00   
IsActiveMember   10000.0  5.151000e-01      0.499797         0.00   
EstimatedSalary  10000.0  1.000902e+05  57510.492818        11.58   
Exited           10000.0  2.037000e-01      0.402769         0.00   

                         25%           50%           75%          max  
RowNumber            2500.75  5.000500e+03  7.500250e+03     10000.00  
CustomerId       15628528.25  1.569074e+07  1.575323e+07  15815690.00  
CreditScore           584.00  6.520000e+02  7.180000e+02       850.00  
Age                    32.00  3.700000e+01  4.400000e+01        92.00  
Tenure                  3.00  5.000000e+00  7.000000e+00        10.00  
Balance                 0.00  9.719854e+04  1.276442e+05    250898.09  
NumOfProducts           1.00  1.000000e+00  2.000000e+00         4.00  
HasCrCard               0.00  1.000000e+00  1.000000e+00         1.00  
IsActiveMember          0.00  1.000000e+00  1.000000e+00         1.00  
EstimatedSalary     51002.11  1.001939e+05  1.493882e+05    199992.48  
Exited                  0.00  0.000000e+00  0.000000e+00         1.00

In [9]:
#also check for correlation matrix

In [10]:
x= dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [12]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [15]:
#data preprocessing through column transformer and one hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,2])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [16]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [17]:
#standard scaling
from sklearn.preprocessing import StandardScaler    # to make the data in  standard format to read
sc = StandardScaler()
x=sc.fit_transform(x)

In [18]:
x

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [19]:
pd.DataFrame(x)

0         1         2         3         4         5         6  \
0     0.997204 -0.578736 -0.573809  1.095988 -1.095988 -0.326221  0.293517   
1    -1.002804 -0.578736  1.742740  1.095988 -1.095988 -0.440036  0.198164   
2     0.997204 -0.578736 -0.573809  1.095988 -1.095988 -1.536794  0.293517   
3     0.997204 -0.578736 -0.573809  1.095988 -1.095988  0.501521  0.007457   
4    -1.002804 -0.578736  1.742740  1.095988 -1.095988  2.063884  0.388871   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.997204 -0.578736 -0.573809 -0.912419  0.912419  1.246488  0.007457   
9996  0.997204 -0.578736 -0.573809 -0.912419  0.912419 -1.391939 -0.373958   
9997  0.997204 -0.578736 -0.573809  1.095988 -1.095988  0.604988 -0.278604   
9998 -1.002804  1.727904 -0.573809 -0.912419  0.912419  1.256835  0.293517   
9999  0.997204 -0.578736 -0.573809  1.095988 -1.095988  1.463771 -1.041433   

             7         8         9        10        11        12  
0    -1.041760 -1.225848 -0.911583  0.646092  0.970243  0.021886  
1    -1.387538  0.117350 -0.911583 -1.547768  0.970243  0.216534  
2     1.032908  1.333053  2.527057  0.646092 -1.030670  0.240687  
3    -1.387538 -1.225848  0.807737 -1.547768 -1.030670 -0.108918  
4    -1.041760  0.785728 -0.911583  0.646092  0.970243 -0.365276  
...        ...       ...       ...       ...       ...       ...  
9995 -0.004426 -1.225848  0.807737  0.646092 -1.030670 -0.066419  
9996  1.724464 -0.306379 -0.911583  0.646092  0.970243  0.027988  
9997  0.687130 -1.225848 -0.911583 -1.547768  0.970243 -1.008643  
9998 -0.695982 -0.022608  0.807737  0.646092 -1.030670 -0.125231  
9999 -0.350204  0.859965 -0.911583  0.646092 -1.030670 -1.076370  

[10000 rows x 13 columns]

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [21]:
from sklearn.svm import SVC
classifier_svc = SVC(kernel='rbf')
classifier_svc.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
y_pred = classifier_svc.predict(x_test)

In [23]:
y_pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [24]:
from sklearn.metrics import confusion_matrix 

In [25]:
confusion_matrix(y_test,y_pred)

array([[1539,   50],
       [ 243,  168]], dtype=int64)

In [26]:
#accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8535

In [27]:
from xgboost import XGBClassifier
classifier= XGBClassifier()           # xgboost application 
classifier.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [28]:
y_pred =classifier.predict(x_test)

In [29]:
confusion_matrix(y_test,y_pred)

array([[1488,  101],
       [ 203,  208]], dtype=int64)

In [30]:
#accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.848

In [31]:
from sklearn.model_selection import cross_val_score
accuracies =cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10,n_jobs=-1)

In [32]:
accuracies

array([0.8675 , 0.85375, 0.855  , 0.86875, 0.86125, 0.855  , 0.8575 ,
       0.865  , 0.83875, 0.855  ])

In [33]:
accuracies.mean()

0.85775

In [34]:
accuracies.std()

0.008250000000000009