In [1]:
import os 
os.chdir("C:\\Users\\Shailesh\\Jupyter Notebook")
os.getcwd()

'C:\\Users\\Shailesh\\Jupyter Notebook'

In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv("Salary_Data.csv")

In [4]:
dataset.head()
x = dataset.iloc[:,0:1].values
y = dataset.iloc[:,-1].values

In [5]:
x


array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [6]:
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=10)

In [8]:
from sklearn.externals import joblib

C:\Users\Shailesh\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [9]:
reg_tr = joblib.load('regressor_joblib')

In [10]:
reg_tr.predict(x_test)

array([89715.76498848, 56031.05821174, 53223.99931368, 40124.39112273,
       44802.8226195 , 92522.82388655])

In [11]:
reg_tr.coef_

array([9356.86299354])

In [12]:
reg_tr.intercept_

26089.096632416717

In [13]:
dataset = pd.read_excel("Book sample.xlsx")

In [14]:
dataset

YearsofExperience
0                   1
1                   2
2                   3
3                   4
4                   5
5                   6
6                   7
7                   8
8                   9
9                  10
10                 11
11                 12
12                 13
13                 14
14                 15

In [15]:
x_new=dataset.iloc[:,0:1].values

In [16]:
x_new

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]], dtype=int64)

In [17]:
reg_tr.predict(x_new) #do concatenation here in dATAFRAME

array([ 35445.95962596,  44802.8226195 ,  54159.68561303,  63516.54860657,
        72873.41160011,  82230.27459365,  91587.13758719, 100944.00058073,
       110300.86357427, 119657.72656781, 129014.58956135, 138371.45255489,
       147728.31554843, 157085.17854197, 166442.04153551])

In [1]:
import pandas as pd

In [5]:
df=pd.DataFrame([[1,2],[4,5],[7,8]],index=['cobra','viper','mamba'],columns=['max_speed','shield'])

In [6]:
df

max_speed  shield
cobra          1       2
viper          4       5
mamba          7       8

In [7]:
df.loc['viper']   # substitute of iloc 

max_speed    4
shield       5
Name: viper, dtype: int64

In [8]:
df.loc[['viper','mamba']]

max_speed  shield
viper          4       5
mamba          7       8

In [10]:
df.loc['cobra','shield']

2

In [12]:
df.loc['cobra':'viper','max_speed']

cobra    1
viper    4
Name: max_speed, dtype: int64

In [13]:
#polynomial regression